name: Github Actions with YAML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CUSTOM_VAR: value
  # Define an environment variable 'CUSTOM_VAR' at the workflow level.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Node.js steps removed because no package.json is present.
      # If you add a package.json, you can restore these steps:
      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # - name: Run tests
      #   run: npm test

  example:
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variable
        run: echo $CUSTOM_VAR
        # Access 'CUSTOM_VAR' in a step.

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: |
          echo "Access Token: ${{ secrets.ACCESS_TOKEN }}"
          # Use 'ACCESS_TOKEN' secret defined in the repository settings.

  conditional-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # The job runs only for push events to the 'main' branch.
    steps:
      - uses: actions/checkout@v2

  outputs-example:
    runs-on: ubuntu-latest
    steps:
      - id: step-one
        run: echo "value=hello" >> $GITHUB_OUTPUT
        # Set an output named 'value' in 'step-one'.
      - id: step-two
        run: |
          echo "Received value from previous step: ${{ steps.step-one.outputs.value }}"
        # Access the output of 'step-one'
